title: Ulysses for Mac
name: ulysses 
keyword: ulysses

| Name   | Command | Note |
| ------ | -----   | ---- |
| create a new sheet | `⌘N` | |
| move a sheet to the trash | `⌘←` | |
| split a sheet at the current cursor location | `⇧⌘B`| |
| create a new group | `⇧⌘N`| |
| create a new filter | `⌃⌘N`| |
|  |  | Items will always be created in vicinity of the current selection. |
|  |  | Sheets will be created below the currently selected sheet. |
|  |  | Groups and filters will be created inside the currently selected group. |
|  |  | If there is no selection, or if the selection can’t accept new content, items will be created in the “Inbox” of the top-most category (e.g. iCloud). |
|  |  | Click to select |
|  |  | Double-click to edit |
[Basic Operation]


| Name   | Command | Note |
| ------ | -----   | ---- |
| toggle the library | `⌘1` | |
| toggle the sheet list | `⌘2` | |
| toggle the editor-only view | `⌘3` | |
| toggle the Attachment Bar | `⌘4` | |
| go to the Favorites group (FIVEorites) | `⌘5` | |
| show Quick Export (SIXport) | `⌘6` | |
| show Statistics | `⌘7` | |
| show the Navigator (NavigEIGHTor, get it?) | `⌘8` | |
| show the Markup Bar | `⌘9` | |
[Basic Operation / Views and Frequently Used Features]

| Name   | Command | Note |
| ------ | -----   | ---- |
| look for a sheet in the whole library | `⌘O`  | |
| look for a sheet in the current library section (iCloud, On My Mac, etc.) | `⇧⌘O` | |
| look for a sheet in the currently selected group | `⌥⌘O` | |
[Basic Operation / Quick Open Panel]


| Name   | Command | Note |
| ------ | -----   | ---- |
| switch focus to the sheet filter | `⇧⌘F` | |
| leave the sheet filter | `esc` | |
[Basic Operation / Global Search]

| Name   | Command | Note |
| ------ | -----   | ---- |
| show the Find panel | `⌘F`  | |
| show the Find & Replace panel | `⌥⌘F` | |
| close the Find/Replace panel | `esc` | |
[Basic Operation / Editor Find & Replace]

| Name   | Command | Note |
| ------ | -----   | ---- |
| add a sheet to or remove it from Favorites | `⌘D` | |
|  |  | You can also use a sheet’s context menu for that. |
| go to the Favorites group (will only be displayed when there are favorited sheets) | `⌘5` | |
[Basic Operation / Favorites]

| Name   | Command | Note |
| ------ | -----   | ---- |
| invoke Smart Paste | `⇧⌘V` | |
| invoke Smart Paste | Hold `⌘V` | Paste options will vary based on clipboard content and current markup |
| preview available paste options | Arrow left/right | `↩︎` to confirm and paste | 
[Basic Operation / Editor Smart Paste]


| Name   | Command | Note |
| ------ | -----   | ---- |
| toggle Dark Theme | `⌥⌘X` | |
| toggle Full Screen Mode | `⌃⌘F` | |
| toggle Dark Mode | `⌥⌘L` | |
[Screen Modes]

| Name   | Command | Note |
| ------ | -----   | ---- |
| New Window | `⌥⌘N` | You can have multiple windows open at the same time |
|  |  | We support macOS’ Split View, so you can display two windows next to each other in Split View. |
|  |  | You can also display a Ulysses sheet next to another app in Split View, or next to its own preview. |
|  |  | You can even have the same sheet visible in all open windows, which makes for some fancy show-off while editing, but it’s of not much use, to be honest. |
[Screen Modes / Multiple Windows, Split View]

| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | The “View” menu holds several options for personalizing the sheet list: |
|  |  |   Set the “Sheet Preview” to anything between 1 and 6 lines. |
|  |  |   Include Keywords and Goals in the sheet preview. |
|  |  |   Either sort manually, by date or by first character. |
[Screen Modes / Sheet List Options]

| Name   | Command | Note |
| ------ | -----   | ---- |
| | | The “View” menu also holds options for personalizing the editor: |
| toggle Typewriter Mode | `⌥⌘T` | |
| | | Enable the display of paragraph numbers |
[Screen Modes / Editor Options]

| Name   | Command | Note |
| ------ | -----   | ---- |
| increase font size | `⌘+` | |
| decrease font size | `⌘-` | |
| reset font size to default value | `⌘0` | |
[Screen Modes / Font Size]


| Name   | Command | Note |
| ------ | -----   | ---- |
| Headlines | `⌘\` | |
| _emphasize_ | `⌘I` | |
| **strong** | `⌘B` | |
| [links] | `⌘K` | |
| removing any sort of Markup | `⌘L` | |
| how the Markup Bar, in case you can’t remember any of this | `⌘9` | |
[Markup]

| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | If enabled, end tag placeholders will automatically be inserted whenever a start tag is followed by a character. |
|  |  | Enable Smart Tags via “Edit › Substitutions”. |
[Markup / Smart Tags]

| Name   | Command | Note |
| ------ | -----   | ---- |
| automatically enter an end tag placeholder. | `esc` | |
|  |  | To accept the end tag, do any of the following: |
|  | Press `↩︎` | |
|  | Press `→` | |
|  | Press `↓` | (if at the very end of a sheet) |
|  | Type in the end tag | |
| Dismiss the end tag, press | `esc` | |
[Markup / End Tag Completion]

| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | To keep Ulysses from treating any character as markup, just add a backslash in front of it (e.g., if you really want a square bracket instead of a link, type “\[something]”). |
[Markup / Escape Character]

| Name   | Command | Note |
| ------ | -----   | ---- |
| show Markup Bar | `⌘9` | When showing the Markup Bar (), you can click on any listed markup to apply it to the current selection. |
| select different parts of your text | `⌘`-Click | This works with multiple selections (`⌘`-Click to select different parts of your text). |
|  |  | Multi-level paragraphs, such as lists and block quotes, will get indented +1 every time you click. |
| either removes the markup or outdents multi-level paragraphs  | `⇧`-Click | |
[Markup / Markup Bar]

| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | By default, Ulysses uses its native markup language “Markdown XL”. |
|  |  | Switch to “Markdown” or “Textile’d” or “Minimark” via “Edit › Convert Markup”. |
|  |  | You can create your own markup via “Preferences › Markup”. |
[Markup / Markup Language]

| Name   | Command | Note |
| ------ | -----   | ---- |
| increase list indentation | `⇥` | |
| decrease list indentation | `⇧⇥` | |
[Lists]

| Name   | Command | Note |
| ------ | -----   | ---- |
| add another list item | `↩︎` | If Smart List is enabled |
| create a new paragraph | `⌥↩︎` | If Smart List is enabled |
|  |  | Enable Smart Lists via “Edit › Substitutions”. |
[Lists / Smart Lists]

| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | Drag’n’drop images and PDFs into the editor to create a text object which holds the item. |
[Lists / Media]

| Name   | Command | Note |
| ------ | -----   | ---- |
| select | `⌘`-Click | |
| open the text object popover. | Double-click | |
[Lists / Text Objects]

| Name   | Command | Note |
| ------ | -----   | ---- |
| close and move insertion point forward | `⌘↩︎` | |
| close and keep object selected | `esc` | |
| switch between input fields | `⇥` | |
- Drag any popover to tear it off and place it anywhere on screen.
[Lists / Text Object Popovers]


| Name   | Command | Note |
| ------ | -----   | ---- |
| to open group | `→` on groups | |
| to switch focus to the sheet list | `→` on groups | |
[Navigation / Library]

| Name   | Command | Note |
| ------ | -----   | ---- |
| switch focus into the editor (placing insertion point at last edited location) | `→` | |
| switch focus into the library | `←` | |
[Navigation / Sheet List]

| Name   | Command | Note |
| ------ | -----   | ---- |
| move one sheet up | Double-tap `↑` | At the start of a sheet |
| move one sheet down | Double-tap `↓` | At the end of a sheet | 
| move one sheet up | `⌥⌘↑` | Anywhere within a sheet |
| move to next sheet |`⌥⌘↓` | Anywhere within a sheet |
| switch focus into the sheet list | Double-tap `⌘←` | | 
[Navigation / Editor]

| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | By default, dragging groups and sheets to and from iCloud or “On My Mac” will always _move_, i.e. contents will get transferred to the new location. |
|  |  | Dragging to and from External Folders will always _copy_, i.e. contents will live in both locations afterwards. |
| force _copy_ of groups and sheets. | Hold `⌥` while dragging |  |
| force _move_ of groups and sheets. | Hold `⌘` while dragging |  |
[Navigation / Copy & Move in Sidebars]


| Name   | Command | Note |
| ------ | -----   | ---- |
| show Quick Export (SIXport) for the current editor | `⌘6` | |
|  |  | You can also right-click on a group, filter or sheet in the sidebar and select “Quick Export…”. |
[Quick Export]

| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | Choose between Plain Text, Rich Text, Markdown and TextBundle output: |
|  |  | 	- “Plain Text” will strip out all tags, comments, annotations, images etc., and only export the text itself. |
|  |  |     - “Rich Text” will produce a simple RTF file. |
|  |  | 	- “Markdown” will keep (or convert) all tags and export the text in Markdown syntax. |
|  |  | 	- [“TextBundle”](http://TextBundle.org) is a new file format which supports embedded images in plain text files. |
[Quick Export / Text Export]

| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | Choose an export style to be applied during export. |
|  |  | Choose between Snippet and Single Page output: |
|  |  | 	- “Snippet” will just convert all tags to HTML and then export the text. |
|  |  | 	- “Single Page” will create a complete HTML document, including header, body, CSS links and so on. |

[Quick Export / HTML Export]

| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | - Choose an export style to be applied during export. |
|  |  | - You can set title and author metadata. |
|  |  | - You can drop an image to be used as cover image for your ebook. |
[Quick Export / ePub Export]

| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | - Choose an export style to be applied during export. |
|  |  | - Choose a paper format. |
[Quick Export / PDF Export]

| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | - Choose an export style to be applied during export. |
|  |  | - Choose a paper format. |
[Quick Export / DOCX Export]

| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | - Ulysses lets you publish directly to Wordpress blogs for which you have editing access: |
|  |  | 	- 1. Choose “Add Account › WordPress/Custom WordPress”. |
|  |  | 	- 2. Provide your Username and Password, and, for a self-hosted WordPress installation, the URL. |
|  |  | 	- 3. Before publishing a post, you can revise its settings (categories, tags, schedule, publishing status and so on.) |
|  |  | - If you own a [Medium](https://medium.com) account, Ulysses allows you to publish your texts as drafts to Medium: |
|  |  | 	- 1. Choose “Add Account › Medium”. |
|  |  | 	- 2. You’ll need to provide an integration token for activation. |
[Quick Export / Publishing]

| Name   | Command | Note |
| ------ | -----   | ---- |
| preview the current sidebar selection (can be groups) | `⇧⌘P` | |
| refresh all open previews | `⌘R` | |
|  |  | Choose an export style to be used for preview |     
|  |  | You can export directly from the preview window. |
[Quick Export / Export Preview]


| Name   | Command | Note |
| ------ | -----   | ---- |
|  |  | You can use Ulysses to edit or respectively import a couple of different file types: |
|  |  |    By default, text and markdown files will appear in the “Open Files” group within your library. All edits and changes will be saved to the original files. |
|  |  |    To _import_ text and markdown files as Ulysses sheets, simply drag them to a group in your library. The original files will stay unaffected from any edits. |
|  |  |    RTF, DOCX and HTML files will always be imported as Ulysses sheets, and will therefore be added to the “Inbox” of your topmost library section. You can of course drag them around at will. |
[Open and Import Files]


| Name   | Command | Note |
| ------ | -----   | ---- |
| create a new version of the current sheet | `⌘S` | Select “Browse All Versions…” from the “File” menu to see how often you invoked that command. |
| jump to the location of your last edit | Double-clicking a sheet in the sheet list | |
[Misc.]
